### ISSUE TITLE
Cannot add isotime to offers query

### ISSUE THREAD

**Issue by kidambisrinivas** [Semantics3/semantics3-python#18]
This works fine:

In [15]: sem3.offers_field("sem3_id", '6HaXu0PKASKgqIqi0a8SSU')
In [16]: prices = sem3.get_offers()

This doesn't:

In [12]: sem3.offers_field("sem3_id", '6HaXu0PKASKgqIqi0a8SSU', "isotime", 1)
In [13]: prices = sem3.get_offers()

**Comment by shawntan** [comment]
If this works the way I remember it should, doing a query like 
```
sem3.offers_field("sem3_id", '6HaXu0PKASKgqIqi0a8SSU', "isotime", 1)
```
should create a nested hash that looks like,
```
{ 'sem3_id': { '6HaXu0PKASKgqIqi0a8SSU': { "isotime": 1 }}}
```

Is that the desired behaviour?

**Comment by kidambisrinivas** [comment]
Nope, so doing it twice should do it?

sem3.offers_field("sem3_id", '6HaXu0PKASKgqIqi0a8SSU')
sem3.offers_field("isotime", 1)

Thanks for the quick response! :)

**Comment by shawntan** [comment]
Yup. Did you try that?

**Comment by kidambisrinivas** [comment]
Yup, that worked for the customer. Thanks
